root@mo066devlwork1:~/test-gw# cat cilium-gateway-class-config.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-nodeport
spec:
  service:
    type: NodePort

root@mo066devlwork1:~/test-gw# vim gateway-class.yaml

root@mo066devlwork1:~/test-gw# kubectl apply -f gateway-class.yaml
gatewayclass.gateway.networking.k8s.io/cilium-nodeport created

root@mo066devlwork1:~/test-gw# kubectl get gatewayclass
NAME              CONTROLLER                     ACCEPTED   AGE
cilium            io.cilium/gateway-controller   True       5d11h
cilium-nodeport   io.cilium/gateway-controller   False      19s

root@mo066devlwork1:~/test-gw# vim gateway.yaml

root@mo066devlwork1:~/test-gw# kubectl apply -f gateway.yaml
gateway.gateway.networking.k8s.io/test-gateway configured

root@mo066devlwork1:~/test-gw# kubectl get gatewayclass
NAME              CONTROLLER                     ACCEPTED   AGE
cilium            io.cilium/gateway-controller   True       5d11h
cilium-nodeport   io.cilium/gateway-controller   False      96s

root@mo066devlwork1:~/test-gw# kubectl get gateway -n test-gw
NAME           CLASS             ADDRESS   PROGRAMMED   AGE
test-gateway   cilium-nodeport             False        19m

root@mo066devlwork1:~/test-gw# kubectl get svc -n test-gw
NAME                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
cilium-gateway-test-gateway   LoadBalancer   10.103.219.199   <pending>     80:31523/TCP   19m
echo                          ClusterIP      10.99.56.34      <none>        80/TCP         20m
