apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo-hpa
  namespace: test-gw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: echo
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


while true; do curl -s http://<LB-IP> > /dev/null; done



