root@mo066devlwork1:~/test-gw# kubectl get svc -n test-gw
NAME                          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
cilium-gateway-test-gateway   LoadBalancer   10.111.117.64   <pending>     80:30561/TCP   4h27m
echo                          ClusterIP      10.96.77.246    <none>        80/TCP         4h59m
root@mo066devlwork1:~/test-gw# kubectl get svc -n test-gw echo -o yaml > 2-service.yaml
root@mo066devlwork1:~/test-gw# vim 2-service.yaml
root@mo066devlwork1:~/test-gw# kubectl apply -f 4-gw-service.yaml
Warning: resource services/cilium-gateway-test-gateway is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
service/cilium-gateway-test-gateway configured
root@mo066devlwork1:~/test-gw# kubectl get svc -n test-gw
NAME                          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
cilium-gateway-test-gateway   LoadBalancer   10.111.117.64   <pending>     80:30561/TCP   4h29m
echo                          ClusterIP      10.96.77.246    <none>        80/TCP         5h1m
root@mo066devlwork1:~/test-gw# kubectl get po -n test-gw
NAME                    READY   STATUS    RESTARTS   AGE
echo-7556b6d69c-6jzqz   1/1     Running   0          5h2m
echo-7556b6d69c-7sfv4   1/1     Running   0          5h2m
root@mo066devlwork1:~/test-gw# curl http://10.140.90.63:30561
upstream connect error or disconnect/reset before headers. reset reason: connection timeoutroot@mo066devlwork1:~/test-gw#
root@mo066devlwork1:~/test-gw#
root@mo066devlwork1:~/test-gw# cat 4-gw-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cilium-gateway-test-gateway
  namespace: test-gw
spec:
  type: NodePort
  selector:
    k8s-app: cilium
  ports:
  - port: 80
    nodePort: 30561
root@mo066devlwork1:~/test-gw# cat 3-gateway.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway
  namespace: test-gw
spec:
  gatewayClassName: cilium
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
  addresses:
    - type: IPAddress
      value: 10.140.90.62
    - type: IPAddress
      value: 10.140.90.63
    - type: IPAddress
      value: 10.140.90.64
    - type: IPAddress
      value: 10.140.90.65
