root@mo066devlwork1:~/test-gw# cat cilium-gateway-class-config.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: cilium-nodeport
spec:
  service:
    type: NodePort
root@mo066devlwork1:~/test-gw# kubectl apply -f cilium-gateway-class-config.yaml
ciliumgatewayclassconfig.cilium.io/cilium-nodeport unchanged
root@mo066devlwork1:~/test-gw# kubectl get ciliumgatewayclassconfigs.cilium.io
NAME              ACCEPTED   AGE
cilium-nodeport   True       16m
root@mo066devlwork1:~/test-gw# cat gateway-class.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-nodeport
spec:
  controllerName: io.cilium/gateway-controller
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: cilium-nodeport
root@mo066devlwork1:~/test-gw# kubectl apply -f gateway-class.yaml
gatewayclass.gateway.networking.k8s.io/cilium-nodeport unchanged
root@mo066devlwork1:~/test-gw# kubectl get gatewayclass
NAME              CONTROLLER                     ACCEPTED   AGE
cilium            io.cilium/gateway-controller   True       5d11h
cilium-nodeport   io.cilium/gateway-controller   False      12m
root@mo066devlwork1:~/test-gw# kubectl describe gatewayclass cilium-nodeport
Name:         cilium-nodeport
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  gateway.networking.k8s.io/v1
Kind:         GatewayClass
Metadata:
  Creation Timestamp:  2026-01-06T05:33:02Z
  Generation:          1
  Resource Version:    3434318
  UID:                 c789fbe0-1c64-48b6-b087-3547ed3195b1
Spec:
  Controller Name:  io.cilium/gateway-controller
  Parameters Ref:
    Group:  cilium.io
    Kind:   CiliumGatewayClassConfig
    Name:   cilium-nodeport
Status:
  Conditions:
    Last Transition Time:  2026-01-06T05:33:02Z
    Message:               Invalid GatewayClass
    Observed Generation:   1
    Reason:                InvalidParameters
    Status:                False
    Type:                  Accepted
Events:                    <none>
